apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: okri
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - cronjobs.yaml
images:
  - name: registry.allvibe.ai/okri/app
    newTag: main
