import type { Language } from "./language";

export type GuideKind = "objective" | "key_result" | "initiative" | "project" | "task";
export const guideKinds: GuideKind[] = ["objective", "key_result", "initiative", "project", "task"];
export const guideTypeNames: Record<GuideKind, string> = { objective: "Objective", key_result: "Key Result", initiative: "Initiative", project: "Project", task: "Task" };
export type GuideCopy = {
  title: string; intro: string; question: string; placeholder: string; start: string; signInNote: string;
  language: string; home: string; share: string; copied: string; shareFallback: string; guideLink: string;
  legalTerms: string; privacy: string;
  example: string; exampleNote: string; expand: string; collapse: string; terms: string;
  baseline: string; target: string; due: string; roles: string; dri: string; assignee: string;
  driDefinition: string; assigneeDefinition: string; roleNote: string;
  structureNote: string; outcomeNote: string; source: string;
  storageError: string; pendingTitle: string; addMessage: string; dismiss: string; pendingNote: string;
  short: Record<GuideKind, string>; definitions: Record<GuideKind, string>;
  objective: string; metrics: [string, string]; initiatives: [string, string];
  projects: [string, string, string, string]; tasks: [string, string, string, string, string, string, string, string];
};

export const guideCopy = {
  ko: {
    title: "OKRI, 목표에서 오늘 할 일까지.",
    intro: "무엇을 이루고 싶은지에서 시작하세요. 성과를 판단할 기준, 실행할 방법, 오늘의 할 일까지 하나로 이어집니다.",
    question: "우리 팀은 무엇을 이루고 싶나요?",
    placeholder: "예: 새 고객이 첫 주 안에 제품의 가치를 경험하게 하고 싶어요.",
    start: "AI와 정리하기", signInNote: "로그인 후 대화를 이어갑니다. 업무는 내용을 확인한 뒤 등록합니다.",
    language: "안내 언어", home: "홈으로 이동", share: "안내 링크 복사", copied: "링크를 복사했어요.", shareFallback: "공유 링크",
    guideLink: "목표와 업무, 한눈에 이해하기",
    legalTerms: "이용약관", privacy: "개인정보처리방침",
    example: "하나의 목표, 연결된 실행", exampleNote: "가상 제품 팀의 예시 · 실제 고객이나 운영 데이터가 아닙니다.",
    expand: "전체 펼치기", collapse: "목표만 보기", terms: "용어를 조금 더 알아보기",
    baseline: "시작", target: "목표", due: "기한", roles: "책임자와 담당자는 무엇이 다를까요?",
    dri: "책임자", assignee: "담당자",
    driDefinition: "Project의 결과와 완료를 끝까지 책임지는 사람. 진행 상황을 살피고, 필요한 협업과 의사결정을 이끕니다.",
    assigneeDefinition: "Task를 직접 수행하는 사람. 구체적인 할 일을 실행하고 진행 상황을 업데이트합니다.",
    roleNote: "책임자가 모든 Task를 직접 수행할 필요는 없습니다. 작은 팀에서는 한 사람이 두 역할을 맡을 수도 있어요.",
    structureNote: "OKR의 중심은 Objective와 Key Result입니다. Initiative → Project → Task는 이를 실행으로 연결하는 OKRI의 구조입니다.",
    outcomeNote: "업무를 끝냈다고 핵심결과가 자동으로 달성되지는 않습니다. Task의 완료와 KR의 실제 수치는 따로 확인합니다.",
    source: "OKR 개념 참고 · What Matters",
    storageError: "이 브라우저에 내용을 임시 보관하지 못했어요. 입력한 내용은 그대로 있으니 브라우저 저장 설정을 확인한 뒤 다시 시도해 주세요.",
    pendingTitle: "안내 페이지에서 적은 목표", addMessage: "메시지에 추가", dismiss: "이 목표 닫기",
    pendingNote: "현재 대화의 메시지에 추가합니다. 기존 초안을 덮어쓰거나 자동으로 보내지 않습니다.",
    short: { objective: "우리가 이루려는 변화", key_result: "목표 달성의 기준", initiative: "성과를 바꿀 실행 전략", project: "범위와 기한을 정한 업무", task: "직접 수행할 구체적인 일" },
    definitions: {
      objective: "우리 팀이 이루고 싶은 의미 있는 변화와 방향입니다.",
      key_result: "목표 달성 여부를 판단하는, 측정 가능한 핵심결과입니다. 지표와 목표 수준을 함께 정합니다.",
      initiative: "핵심결과를 개선하기 위해 선택한 실행 전략입니다. 효과를 확인하며 방법을 바꿀 수 있습니다.",
      project: "실행 전략을 옮기는, 결과·범위·기한이 정해진 업무 묶음입니다.",
      task: "Project를 진행하기 위해 완료해야 할 구체적인 할 일입니다.",
    },
    objective: "새 고객이 첫 주 안에 제품의 가치를 경험하게 한다.",
    metrics: ["첫 7일 안에 핵심 기능을 사용하는 고객 비율", "신규 고객의 첫 달 유지율"],
    initiatives: ["첫 사용 여정을 단순하게 만든다.", "다시 방문할 이유를 만든다."],
    projects: ["핵심 기능 시작 흐름 개편", "첫 성과를 만드는 시작 템플릿", "첫 달 고객 피드백 프로그램", "다음 사용을 안내하는 요약 메일"],
    tasks: ["가입 후 이탈 구간을 분석한다.", "첫 실행 단계를 줄인 시안을 테스트한다.", "고객의 첫 사용 목적을 분류한다.", "목적별 시작 템플릿을 배포한다.", "첫 달 고객 5명을 인터뷰한다.", "반복되는 불편을 정리하고 개선안을 정한다.", "고객이 다음에 할 행동을 정의한다.", "요약 메일의 재방문 효과를 실험한다."],
  },
  en: {
    title: "OKRI, from goals to today's work.",
    intro: "Start with what you want to achieve. Connect your measures of success, your approach, and the work you do today.",
    question: "What would your team like to achieve?",
    placeholder: "For example: Help new customers experience our product's value in their first week.",
    start: "Shape it with AI", signInNote: "Continue the conversation after signing in. Review the details before creating any work.",
    language: "Guide language", home: "Go to home", share: "Copy guide link", copied: "Link copied.", shareFallback: "Share link",
    guideLink: "See how goals and work connect",
    legalTerms: "Terms of service", privacy: "Privacy policy",
    example: "One goal. Connected work.", exampleNote: "A fictional product team example, not customer or production data.",
    expand: "Expand all", collapse: "Show only the goal", terms: "A closer look at the terms",
    baseline: "Starting point", target: "Target", due: "Due", roles: "Who owns the outcome, and who does the work?",
    dri: "Project lead", assignee: "Assignee",
    driDefinition: "The person accountable for a Project's outcome and completion. They track progress and coordinate the collaboration and decisions needed.",
    assigneeDefinition: "The person who carries out a Task and keeps its progress up to date.",
    roleNote: "The Project lead does not need to do every Task. In a small team, one person can hold both roles.",
    structureNote: "Objectives and Key Results are the core of OKRs. Initiative → Project → Task is how OKRI connects them to execution.",
    outcomeNote: "Completing work does not automatically achieve a Key Result. Track Task completion and the actual KR metric separately.",
    source: "OKR concepts · What Matters",
    storageError: "This browser could not keep your text temporarily. Your text is still here. Check browser storage settings and try again.",
    pendingTitle: "The goal you wrote in the guide", addMessage: "Add to message", dismiss: "Dismiss this goal",
    pendingNote: "Add this to the current conversation's message. Your existing draft stays intact, and nothing is sent automatically.",
    short: { objective: "The change we want", key_result: "Our measure of success", initiative: "Our approach to change", project: "Work with scope and a deadline", task: "A specific action to complete" },
    definitions: {
      objective: "The meaningful change and direction your team wants to achieve.",
      key_result: "A measurable result that tells you whether you have achieved the Objective. Define both the metric and the target.",
      initiative: "An approach chosen to improve a Key Result. Adjust it as you learn what works.",
      project: "A defined body of work that puts an Initiative into practice, with an outcome, scope, and deadline.",
      task: "A concrete action to complete in order to move a Project forward.",
    },
    objective: "Help new customers experience the product's value in their first week.",
    metrics: ["Share of customers using a core feature within 7 days", "First-month retention of new customers"],
    initiatives: ["Simplify the first-use journey.", "Create reasons to return."],
    projects: ["Redesign the core-feature start flow", "Starter templates for a first win", "First-month customer feedback program", "A recap email with a useful next step"],
    tasks: ["Analyze drop-off points after sign-up.", "Test a prototype with fewer first-use steps.", "Group customers by their first-use goal.", "Publish starter templates for each goal.", "Interview 5 first-month customers.", "Identify recurring friction and agree on improvements.", "Define the customer's next useful action.", "Test the recap email's effect on return visits."],
  },
  ja: {
    title: "OKRI、目標から今日の仕事まで。",
    intro: "実現したいことから始めましょう。成果を判断する基準、取り組む方法、今日の仕事がひとつにつながります。",
    question: "チームで何を実現したいですか？",
    placeholder: "例：新規顧客が最初の1週間で製品の価値を実感できるようにしたい。",
    start: "AIと整理する", signInNote: "ログイン後に会話を続けられます。内容を確認してから仕事を登録します。",
    language: "ガイドの言語", home: "ホームへ移動", share: "ガイドのリンクをコピー", copied: "リンクをコピーしました。", shareFallback: "共有リンク",
    guideLink: "目標と仕事のつながりを見る",
    legalTerms: "利用規約", privacy: "プライバシーポリシー",
    example: "ひとつの目標、つながる実行", exampleNote: "架空の製品チームの例です。実際の顧客や運用データではありません。",
    expand: "すべて展開", collapse: "目標だけ表示", terms: "用語をもう少し詳しく",
    baseline: "開始時点", target: "目標", due: "期限", roles: "責任者と担当者はどう違う？",
    dri: "責任者", assignee: "担当者",
    driDefinition: "Projectの成果と完了に責任を持つ人です。進捗を確認し、必要な連携や意思決定を進めます。",
    assigneeDefinition: "Taskを実際に遂行し、進捗を更新する人です。",
    roleNote: "責任者がすべてのTaskを行う必要はありません。小さなチームでは、一人が両方を担うこともあります。",
    structureNote: "OKRの中心はObjectiveとKey Resultです。Initiative → Project → Taskは、それを実行につなげるOKRIの構造です。",
    outcomeNote: "仕事の完了だけでKey Resultが達成されるわけではありません。Taskの完了とKRの実測値を別々に確認します。",
    source: "OKRの考え方 · What Matters",
    storageError: "このブラウザーに文章を一時保存できませんでした。入力内容はそのままです。保存設定を確認して再試行してください。",
    pendingTitle: "ガイドで書いた目標", addMessage: "メッセージに追加", dismiss: "この目標を閉じる",
    pendingNote: "現在の会話のメッセージに追加します。既存の下書きは上書きせず、自動送信もしません。",
    short: { objective: "実現したい変化", key_result: "達成を判断する基準", initiative: "成果を変える実行戦略", project: "範囲と期限を定めた仕事", task: "実際に完了する具体的な仕事" },
    definitions: {
      objective: "チームが実現したい、意義のある変化と方向性です。",
      key_result: "目標の達成を判断する、測定可能な成果です。指標と目標水準を合わせて定めます。",
      initiative: "Key Resultを改善するために選んだ実行戦略です。効果を確認しながら方法を変えられます。",
      project: "戦略を実行に移す、成果・範囲・期限の決まった仕事のまとまりです。",
      task: "Projectを進めるために完了すべき具体的な仕事です。",
    },
    objective: "新規顧客が最初の1週間で製品の価値を実感できるようにする。",
    metrics: ["最初の7日以内に主要機能を使う顧客の割合", "新規顧客の初月継続率"],
    initiatives: ["初回利用の流れをシンプルにする。", "再訪する理由をつくる。"],
    projects: ["主要機能の開始フローを改善", "最初の成果を生むテンプレート", "初月の顧客フィードバック施策", "次の行動を案内する振り返りメール"],
    tasks: ["登録後に離脱する箇所を分析する。", "初回の操作を減らした試作をテストする。", "顧客の初回利用の目的を分類する。", "目的別の開始テンプレートを公開する。", "初月の顧客5人にインタビューする。", "共通の不便を整理し改善策を決める。", "顧客の次の有益な行動を定義する。", "メールが再訪に与える効果を検証する。"],
  },
  zh: {
    title: "OKRI，从目标到今天的工作。",
    intro: "从想实现的改变开始。把衡量成果的标准、行动方法和今天的工作连接起来。",
    question: "你的团队想实现什么？",
    placeholder: "例如：让新客户在第一周就体验到产品的价值。",
    start: "与 AI 一起梳理", signInNote: "登录后继续对话，确认内容后再创建工作。",
    language: "指南语言", home: "返回首页", share: "复制指南链接", copied: "链接已复制。", shareFallback: "分享链接",
    guideLink: "看懂目标与工作的连接",
    legalTerms: "服务条款", privacy: "隐私政策",
    example: "一个目标，彼此连接的行动", exampleNote: "虚构产品团队示例，并非真实客户或运营数据。",
    expand: "全部展开", collapse: "只看目标", terms: "进一步了解这些概念",
    baseline: "起点", target: "目标值", due: "截止", roles: "负责人和执行人有什么不同？",
    dri: "负责人", assignee: "执行人",
    driDefinition: "对 Project 的成果与完成负责的人。他们跟进进度，推动所需的协作与决策。",
    assigneeDefinition: "实际执行 Task 并更新进度的人。",
    roleNote: "负责人不必亲自执行每项 Task。在小团队中，同一个人也可以兼任两种角色。",
    structureNote: "OKR 的核心是 Objective 和 Key Result。Initiative → Project → Task 是 OKRI 将其连接到执行的结构。",
    outcomeNote: "完成工作不代表自动达成 Key Result。Task 完成情况与 KR 的实际数值需要分别确认。",
    source: "OKR 概念参考 · What Matters",
    storageError: "此浏览器无法临时保存文字。输入内容仍在，请检查浏览器存储设置后重试。",
    pendingTitle: "你在指南中写下的目标", addMessage: "添加到消息", dismiss: "关闭此目标",
    pendingNote: "添加到当前对话的消息中，不覆盖已有草稿，也不会自动发送。",
    short: { objective: "我们想实现的改变", key_result: "判断目标达成的标准", initiative: "改善成果的执行策略", project: "有范围和期限的工作", task: "具体要完成的行动" },
    definitions: {
      objective: "团队想实现的、有意义的改变与方向。",
      key_result: "用于判断目标是否达成的可衡量成果，同时明确指标与目标水平。",
      initiative: "为改善 Key Result 而选择的执行策略，可根据实际效果调整方法。",
      project: "将策略付诸实践、明确成果、范围和期限的一组工作。",
      task: "为推进 Project 而需要完成的具体事项。",
    },
    objective: "让新客户在第一周就体验到产品的价值。",
    metrics: ["前 7 天内使用核心功能的客户比例", "新客户首月留存率"],
    initiatives: ["简化首次使用流程。", "创造再次访问的理由。"],
    projects: ["改进核心功能的入门流程", "帮助获得初次成果的入门模板", "首月客户反馈计划", "引导下一步行动的总结邮件"],
    tasks: ["分析注册后的流失环节。", "测试减少首次操作步骤的原型。", "按首次使用目的对客户分类。", "发布适用于不同目的的入门模板。", "访谈 5 位首月客户。", "归纳常见问题并确定改进方案。", "明确客户下一步有价值的行动。", "测试总结邮件对再次访问的影响。"],
  },
  es: {
    title: "OKRI, de los objetivos al trabajo de hoy.",
    intro: "Empieza por lo que quieres lograr. Conecta las medidas de éxito, tu enfoque y el trabajo de cada día.",
    question: "¿Qué quiere lograr tu equipo?",
    placeholder: "Por ejemplo: Que los nuevos clientes descubran el valor del producto en su primera semana.",
    start: "Organizarlo con IA", signInNote: "Continúa la conversación después de iniciar sesión. Revisa los detalles antes de crear trabajo.",
    language: "Idioma de la guía", home: "Ir al inicio", share: "Copiar enlace de la guía", copied: "Enlace copiado.", shareFallback: "Enlace para compartir",
    guideLink: "Descubre cómo se conectan objetivos y trabajo",
    legalTerms: "Términos de servicio", privacy: "Política de privacidad",
    example: "Un objetivo. Trabajo conectado.", exampleNote: "Ejemplo de un equipo ficticio, no datos de clientes ni de producción.",
    expand: "Expandir todo", collapse: "Ver solo el objetivo", terms: "Conoce mejor los conceptos",
    baseline: "Punto de partida", target: "Meta", due: "Fecha límite", roles: "¿Quién responde por el resultado y quién ejecuta el trabajo?",
    dri: "Responsable", assignee: "Persona asignada",
    driDefinition: "La persona que responde por el resultado y la finalización del Project. Sigue el progreso y coordina la colaboración y las decisiones necesarias.",
    assigneeDefinition: "La persona que ejecuta una Task y mantiene actualizado su progreso.",
    roleNote: "La persona responsable no tiene que ejecutar todas las Task. En equipos pequeños, una persona puede asumir ambos roles.",
    structureNote: "Objective y Key Result son el núcleo de los OKR. Initiative → Project → Task es la estructura de OKRI para conectarlos con la ejecución.",
    outcomeNote: "Completar trabajo no garantiza alcanzar un Key Result. Comprueba por separado las Task completadas y la métrica real del KR.",
    source: "Conceptos de OKR · What Matters",
    storageError: "El navegador no pudo conservar el texto temporalmente. El texto sigue aquí. Revisa los ajustes de almacenamiento e inténtalo de nuevo.",
    pendingTitle: "El objetivo que escribiste en la guía", addMessage: "Añadir al mensaje", dismiss: "Descartar este objetivo",
    pendingNote: "Se añade al mensaje de la conversación actual. No se sobrescribe tu borrador ni se envía automáticamente.",
    short: { objective: "El cambio que buscamos", key_result: "Nuestra medida de éxito", initiative: "El enfoque para mejorar", project: "Trabajo con alcance y plazo", task: "Una acción concreta que completar" },
    definitions: {
      objective: "El cambio significativo y la dirección que tu equipo quiere alcanzar.",
      key_result: "Un resultado medible que permite saber si se ha logrado el Objective. Define tanto la métrica como su meta.",
      initiative: "Un enfoque elegido para mejorar un Key Result. Se puede ajustar según lo que funcione.",
      project: "Un conjunto de trabajo que pone en práctica una Initiative, con resultado, alcance y plazo definidos.",
      task: "Una acción concreta que hay que completar para avanzar en un Project.",
    },
    objective: "Que los nuevos clientes descubran el valor del producto en su primera semana.",
    metrics: ["Clientes que usan una función principal en los primeros 7 días", "Retención de nuevos clientes durante el primer mes"],
    initiatives: ["Simplificar la primera experiencia.", "Crear motivos para volver."],
    projects: ["Rediseñar el inicio de la función principal", "Plantillas para un primer logro", "Programa de comentarios del primer mes", "Un correo resumen con el siguiente paso"],
    tasks: ["Analizar dónde se abandona el proceso tras registrarse.", "Probar un prototipo con menos pasos iniciales.", "Agrupar clientes según su primer propósito de uso.", "Publicar plantillas de inicio para cada propósito.", "Entrevistar a 5 clientes de su primer mes.", "Identificar problemas recurrentes y acordar mejoras.", "Definir la siguiente acción útil para el cliente.", "Probar el efecto del correo en las visitas de regreso."],
  },
} satisfies Record<Language, GuideCopy>;

export function getGuideCopy(language: Language): GuideCopy { return guideCopy[language]; }
